#!/bin/sh

# script that calls pywal to a random image and links it to img_lock

img_dir="${HOME}/Media/Pictures/Wallpapers"
img_lock="${XDG_DATA_HOME:-$HOME/.local/share}/bg"
#backend=wal		# colorz - schemer2 - wal - haishoku - colorthief

# post run hooks, everything here runs in the background
postrun() {
	xwallpaper --zoom "$img_lock"
	killall --quiet glava && glava 1>/dev/null
	#killall --quiet -9 dunst && dunst
}

random_img="$(fd . "$img_dir" -e jpg -e jpeg -e png --type f | shuf -n 1)"
#randomimg="$(find "$img_path" -iregex '.*.\(jpg\|jpeg\|png\)' -type f | shuf -n 1)"

#wal -i "$random_img" --backend $backend -qnt && demwm xrdb
wallust -q "$random_img" && xrdb -merge -quiet ~/.config/Xresources && demwm xrdb

ln -sf "$random_img" "$img_lock"

postrun &
