.TH DEMWM 1 demwm-VERSION
.SH "NAME"
.PP
demwm - Dynamic Explosion-Mental’s Window Manager
.SH "SYNOPSIS"
.PP
\fBdemwm\fP [ \fBfunction\fP ] (argument)
.SH "DESCRIPTION"
.PP
A custom fork of dwm(1), a (tiling) window manager for X. You have customs \fBrules\fP and \fBlayouts\fP to use and set that handles clients in different ways.


.PP
Windows are grouped by tags. Each window can be tagged with one or multiple tags. Selecting certain tags displays all windows with these tags.


.PP
Each monitor has it’s own set of tags and therefore, one window can only belong to one monitor; meaning you can’t view the same window in two different \fBindependent\fP monitors, of course this is possible if you mirror in between outputs (monitors).


.PP
The status bar text is filled with command outputs (stdout) defined in config.h. \fBdemwm\fP will use the greatest common divisor of the \fBinterval\fP value of the \fBblocks\fP array to have a constant value in order to call and update blocks that need it, so keep an eye on this. This will only display on the selected monitor.

.PP
\fIA note about usage\fP: The status text is done by the poll(3) system call, this exec(3)’s scripts every \fCX\fP (determined by the Greatest Common Divisor) seconds \fBasynchronously\fP, which of course stock dwm doesn’t. You won’t notice any change in resources if you normally use \fCdwmblocks\fP or it’s variants (all of them exec(3) scripts).


.PP
If the bar or the statustext it’s hidden, there would be \fBno\fP need to call poll(3) and status blocks won’t \fBever\fP be exec(3)uted.


.PP
\fBdemwm\fP also acts as an “\fIclient\fP” program, which calls the window manager to do certain actions. See IPC section.
.SH "OPTIONS"
.PP
Without any arguments, the program will try to initialize the window manager.
For information about the kind of arguments check out FUNCTIONS and IPC sections
.br

.PP
\fINOTE\fP: Functions that do take an argument, are (\fImostly\fP) \fBbidirectional\fP: this means that number signs define the behaviour of the function. ( \fC\-1\fP / \fC+1\fP )
.SH "SIGNALS"
.PP
Earlier versions of demwm used SIGHUP and SIGTERM for restarting and quitting the window manager respectively. This is now handled by the argument \fBrestart\fP and \fBquit\fP. See IPC section.
.SH "ENVIROMENT"
.SS "BLOCK_\d\s-2BUTTON\s+2\u"
.PP
For clicking to do anything you have to make a dedicated script which handles
the \fCBLOCK_BUTTON\fP \fIenviromental variable\fP. See EXAMPLES section.
.br
To define the value of \fCBLOCK_BUTTON\fP, you have to edit \fBconfig.h\fP mouse
buttons bindings \fCsendstatusbar\fP.
.br
This \fIenviromental variable\fP is only set to the script session being called.
.SH "CONFIGURATION"
.PP
dwm is customized by creating a custom config.h and (re)compiling the source code. This keeps it simple, since reading a config file isn’t that hard (but adds unneeded complexity), and in many aspects more customizable. I try my best to comment about the variables in config.h, since they don’t do anything crazy, so it should be very straight foward what does what.
.br
.SH "STATUS BAR TEXT BLOCKS"
.TS
 center,box;

l |l |.
\fBEntry\fP	\fBValue\fP
_
\fBscheme\fP	Select a scheme to use for the block, can be a default one
	(e.g. SchemeTitle) or you can create one by using \fCSchemeLast+X\fP
	where \fCX\fP is a number starting from 0, this number increases
	depending on how many schemes you make.
_
\fBcommand\fP	A command (e.g. \fCecho 'Hello World'\fP) which output will become
	this block text.
_
\fBinterval\fP	How many seconds have to pass before updating (running/executing)
	the command and update the output. Can be 0, which means never.
_
\fBsignal\fP	A number used to manually update the block.
	Can be 0, which won’t allow you to signal the block.
.TE
.TB ""

.SH "IPC"
.PP
Mostly for scripting or to do certain things without a need of a keybinding,
freeing the keyboard with functions that you might use once in a while.

.PP
To use this you only need to call \fBdemwm\fP with a function and it’s respective
argument if any. See FUNCTIONS section for avaliable functions. Some of which aren’t avaliable/intendent to use as an ipc command and thus it’s noted, otherwise the function is included and avaliable to use.
.SH "FUNCTIONS"
.SS "cyclelayout"
.PP
Moves the layouts index depending on the argument.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "combotag"
.PP
Select multiple tags to \fCtag\fP by pressing all the right keys as a combo: you can press multiple tags by holding the modifier(s) keys (MOD by default).
.br

.PP
Takes an (unsigned) int which indicates the tag as an exponent of \fC2\fP. Just define it as \fC1 << TAG\fP where TAG is the tag you wish (starting from 0).
.br

.PP
\fINOTE\fP: This is not avaliable as an IPC function.
.SS "comboview"
.PP
Select multiple tags to \fCview\fP by pressing all the right keys as a combo: you can press multiple tags by holding the modifier(s) keys (MOD by default).
.br

.PP
Takes an (unsigned) int which indicates the tag as an exponent of \fC2\fP. Just define it as \fC1 << TAG\fP where TAG is the tag you wish (starting from 0).
.br

.PP
\fINOTE\fP: This is not avaliable as an IPC function.
.SS "defaultgaps"
.PP
Set the gaps to the values defined in config.h.
.br

.PP
No arguments.
.SS "focusmon"
.PP
Focus monitor
.br

.PP
It takes an \fIinteger\fP argument.
.SS "focusstack"
.PP
More like, ’focus client’. Focuses the next/prev client (window).
.br

.PP
Takes an \fIinteger\fP as an argument.
.SS "incnmaster"
.PP
Increase master, sutracts/adds the first stack (slave) window to the master stack (left side on default tile layout).
.br

.PP
It takes an \fIinteger\fP argument.
.SS "incrgaps"
.PP
Increases or decreses \fBinner\fP, \fBouter\fP, \fBvertical\fP and \fBhorizontal\fP gaps by the argument given.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "incrigaps"
.PP
Increases or decreses the \fBinner\fP, \fBvertical\fP and \fBhorizontal\fP gaps by the argument given.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "incrihgaps"
.PP
Increases or decreses the \fBinner\fP, and \fBhorizontal\fP gaps by the argument given.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "incrivgaps"
.PP
Increases or decreses the \fBinner\fP and \fBvertical\fP gaps by the argument given.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "incrogaps"
.PP
Increases or decreses the \fBouter\fP, \fBvertical\fP and \fBhorizontal\fP gaps by the argument given.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "incrohgaps"
.PP
Increases or decreses the \fBouter\fP, and \fBhorizontal\fP gaps by the argument given.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "incrovgaps"
.PP
Increases or decreses the \fBouter\fP and \fBvertical\fP gaps by the argument given.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "killclient"
.PP
The name describe it, kills a window client.
.br

.PP
No arguments.
.SS "movefh\d\s-2setmfact\s+2\u"
.PP
A custom fuction of mine which reuses two functions: \fBmovefloathoriz\fP and \fBsetmfact\fP
This is just because setmfact has no effect if I have a floating window.
.br

.PP
It takes an \fIfloat\fP argument and passes it to \fCsetmfact\fP. The argument for the \fCmovefloathoriz\fP is defined in config.h as the variable \fCmovefloat\fP.
.br

.PP
\fINOTE\fP: This is not avaliable as an IPC function. Since this function is for personal use to be able to \fBreuse\fP the same keybinding.
.SS "movefloathorz"
.PP
Moves the current \fBfloating\fP windows horizontaly by the argument given.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "movefloatvert"
.PP
Moves the current \fBfloating\fP windows verticaly by the argument given.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "movefv\d\s-2pushstack\s+2\u"
.PP
A custom fuction of mine which reuses two functions: \fBmovefloatvert\fP and \fBpushstack\fP
This is just because \fBpushstack\fP has no effect if I have a floating window.
.br

.PP
It takes an \fIinteger\fP argument and passes it to \fCpushstack\fP. The argument for the \fCmovefloatvert\fP is defined in config.h as the variable \fCmovefloat\fP.
.br

.PP
\fINOTE\fP: This is not avaliable as an IPC function. Since this function is for personal use to be able to \fBreuse\fP the same keybinding.
.SS "pushstack"
.PP
\fIPushes\fP the current client to be the next/previous client in the stack.
.br
Note: Currently with this function the client can become the master, this is not intended since for this we have \fBzoom\fP.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "quit"
.PP
Quits demwm.
.br

.PP
No arguments.
.SS "refresh"
.PP
Restarts or refreshes the current \fBdemwm\fP instance.
This keeps all clients into their tags and corresponding monitors, as well as leaves the clients in a floating state and fullscreened, in case they have that property.
This won’t keep the layouts of the tags, the state of gaps (enabled/disabled), master/slaves relations, etc. If you wish these \fIworkspace\fP like feature, checkout dusk(1).
.br

.PP
No arguments.
.SS "scratchpad\d\s-2hide\s+2\u"
.PP
Adds the current client to the \fBdynamic\fP scratchpads list, hiding it. See SCRATCHPADS section.
.br

.PP
No arguments.
.SS "scratchpad\d\s-2remove\s+2\u"
.PP
Removes the current client to the \fBdynamic\fP scratchpads list. See SCRATCHPADS section.
.br

.PP
No arguments.
.SS "scratchpad\d\s-2show\s+2\u"
.PP
Show a dynamic scratchpad from the list. If more than one window exist in the list, this functions cycles between them from first to last added. See SCRATCHPADS section.
.br

.PP
No arguments.
.SS "setmfact"
.PP
\fBSets\fP the \fBmaster\fP \fBfactor\fP area, modifies the \fCmfact\fP (master factor area) value at runtime.
.br

.PP
It takes a \fIfloat\fP argument, between \fC0.05\fP and \fC0.95\fP.
.SS "shiftboth"
.PP
\fCshiftview\fP + \fCshifttag\fP
.br

.PP
It takes an \fIinteger\fP argument.
.SS "shifttag"
.PP
\fCtag\fP the current window to the next/previous \fIN\fP tag. \fIN\fP being defined by the argument.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "shifttagclients"
.PP
\fCtag\fP the current window to the next/previous \fIN\fP \fBoccupied\fP tag, a tag with at least one client. \fIN\fP being defined by the argument.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "shiftview"
.PP
\fCview\fP the current window to the next/previous \fIN\fP tag. \fIN\fP being defined by the argument.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "shiftviewclients"
.PP
\fCview\fP the current window to the next/previous \fIN\fP \fBoccupied\fP tag, a tag with at least one client. \fIN\fP being defined by the argument.
.br

.PP
It takes an \fIinteger\fP argument.
.SS "spawn"
.PP
A wrapper for \fIexec\fP function. This executes shell commands.
.br

.PP
It takes a \fIvoid\fP argument: an array of chars with a last element of \fBNULL\fP. The wrapper macro \fBSHCMD\fP sets \fC/bin/sh \-c\fP as the command, which allows you to do shell tricks (\fC&&\fP, \fC||\fP, \fC&\fP, etc)
.br

.PP
\fINOTE\fP: This is not avaliable as an IPC function.
.SS "swaptags"
.PP
Changes, \fIswaps,\fP the contents (windows) of the current tag with the tag defined in the argument.
.br

.PP
Takes an (unsigned) int which indicates the tag as an exponent of \fC2\fP. Just define it as \fC1 << TAG\fP where TAG is the tag you wish (starting from 0).
.br

.PP
\fINOTE\fP: If used in IPC, the above will be done automatically, e.g.: \fCdemwm tag 0\fP will \fIswap\fP windows with tag 0 (first tag) without the need of manually shifting (\fC1 << 0\fP).
.SS "tag"
.PP
“\fItag\fP” the current window to a tag. Basically like moving the windows to a ’workspace’ or a “\fIdifferent desktop\fP”, which is only a way of thinking since dwm doesn’t implements those.
.br

.PP
Takes an (unsigned) int which indicates the tag as an exponent of \fC2\fP. Just define it as \fC1 << TAG\fP where TAG is the tag you wish (starting from 0).
.br

.PP
\fINOTE\fP: If used in IPC, the above will be done automatically, e.g.: \fCdemwm tag 0\fP will put the current selected window to tag 0 (first tag) without the need of manually shifting (\fC1 << 0\fP).
.SS "tagmon"
.PP
Like \fCtag\fP but to the other monitor. Sends the window to the next monitor (display 0, 1, etc..).
.br

.PP
It takes an \fIinteger\fP argument.
.SS "togglealwaysontop"
.PP
Add or remove the \fIalwaysontop\fP state of a client. \fBAlwaysontop\fP means to be on top of all windows (including the bar), useful when combined with the sticky flag.
.br

.PP
No arguments.
.SS "togglebar"
.PP
(Un)hides the bar.
.br

.PP
No arguments.
.SS "toggletagbar"
.PP
(Un)hides the bar only for the current tag.
.br

.PP
No arguments.
.SS "togglefakefullscreen"
.PP
Add or remove the \fIfakefullscreen\fP state property of the client. \fBFakeFullScreen\fP means to have the window in a fullscreen state, in a window basis, but treat it as a normal window, in a window manager basis. This results in having fullscreened windows that can be tiled, floating, etc. and the window doesn’t necessarily occupies the hole screen.
.br

.PP
No arguments.
.SS "togglefloating"
.PP
Toggles floating behaviour on windows. This depends on the current state of the window.
.br

.PP
No arguments.
.SS "togglefullscreen"
.PP
Add or remove the \fIfullscreen\fP state property of the client.
.br

.PP
No arguments.
.SS "togglestatus"
.PP
(Un)hides the status text blocks, keeping the bar up if active.
.br

.PP
No arguments.
.SS "togglesticky"
.PP
Add or remove the \fIsticky\fP state of a client. \fBSticky\fP means that the window will be visible in all tags.
.br

.PP
No arguments.
.SS "toggletag"
.PP
Like tag but it can stack, meaning you can ’tag’ multiple tags. This is toggleable.
.br

.PP
Takes an (unsigned) int which indicates the tag as an exponent of \fC2\fP. Just define it as \fC1 << TAG\fP where TAG is the tag you wish (starting from 0).
.br

.PP
\fINOTE\fP: If used in IPC, the above will be done automatically, e.g.: \fCdemwm toggletag 1\fP will add the current selected window to tag 1 (second tag) without the need of manually shifting (\fC1 << 1\fP).
.SS "toggletopbar"
.PP
Inverse the position of the bar. If the bar is on the top, puts it on the bottom; if the bar is on the bottom, puts it on the top.
.br

.PP
No arguments.
.SS "togglevacant"
.PP
(Un)hides the vacant (empty) tags.
.br

.PP
No arguments.
.SS "toggleview"
.PP
Like view but it can stack, meaning you can ’view’ multiple tags. This is toggleable.
.br

.PP
Takes an (unsigned) int which indicates the tag as an exponent of \fC2\fP. Just define it as \fC1 << TAG\fP where TAG is the tag you wish (starting from 0).
.br

.PP
\fINOTE\fP: If used in IPC, the above will be done automatically, e.g.: \fCdemwm tag 8\fP will put the current selected window to tag 8 (ninth tag) without the need of manually shifting (\fC1 << 8\fP).
.SS "updateblock"
.PP
updates a status bar block text.
.br

.PP
It takes an (unsigned) \fIinteger\fP argument, which correspond to the signal number of the block you wish to update.
.br

.PP
\fINote for usage in config.h\fP: Since the blocks updates are asynchronous (in the background), the signaling is ’instantaneous’. Say you have a same keybinding that executes some command related to the status block, and you also define the same keybinding to update the block using this function; most likely updating the block will be faster and thus the block will not be affected by the other command (doesn’t matter as a demwm argument).
.SS "view"
.PP
View the contents of a tag, you can think of it like moving to a tag.
.br

.PP
Takes an (unsigned) int which indicates the tag as an exponent of \fC2\fP. Just define it as \fC1 << TAG\fP where TAG is the tag you wish (starting from 0).
.br

.PP
\fINOTE\fP: If used in IPC, the above will be done automatically, e.g.: \fCdemwm tag 0\fP will put the current selected window to tag 0 (first tag) without the need of manually shifting (\fC1 << 0\fP).
.SS "xrdb"
.PP
Refreshes or reloads the colors, reads their Xresource value and arranges all the monitors (which actually displays the new colors, if any).
.br

.PP
No arguments.
.SS "zoom"
.PP
Swaps between the first window on the master stack to the current window. If you are already on the first master window, it uses the second master window.
.br

.PP
No arguments.
.SS "zoomswap"
.PP
Variation of the \fCzoom\fP function that maintains the positions of the windows.
.br

.PP
No arguments.
.SH "SCRATCHPADS"
.PP
I have two patches: \fIscratchpads\fP and \fIdynamic scratchpads\fP. Both of these do different functions so they work well so here goes a bit of explanation:
.SS "dynamic scratchpads"
.PP
Any window can be added or removed as a scratchpad. You can add multiple clients to this “\fIlist\fP” of dynamic scratchpads but the catch is that to get to a certain client the binding will cycle through them (meaning more key presses).
.SS "static scratchpads"
.PP
Allows you  to \fIstore\fP a client on a tag that isn’t visible. When you call that client by pressing a keybinding you basically \fCtoggleview\fP that tag and you will see the client store. This scratchpad can be maintained (called) between multiple monitors.
.br

.PP
For this you need to define a \fCRule\fP for that client (res name or class) and add it to the tag \fCSP(X)\fP, which X represents the same index in the array of the \fCscratchpads\fP array. For simpler understanding just use the sample variables I defined which are \fCSp1\fP to \fCSp9\fP and make sure these match in between the \fCRule\fP tags, the binding and the definition of the command inside the array \fCscratchpads\fP.
.SH "EXAMPLES"
.SS "Usage of \fCspawn\fP and \fCSHCMD\fP"
.RS
.nf
\fCstatic const char *ncmpcpp[] = { "st", "-e", "ncmpcpp", NULL };
static Key keys[] = {
  /* modifier(s)      key         function        argument        */
  { MODKEY            XK_n,       spawn,      { .v = ncmpcpp }    },
  { MODKEY            XK_m,       SHCMD("st -e ncmpcpp")          },
  ...
};
\fP
.fi
.RE
.SS "Defining a \fBstatic\fP scratchpad"
.RS
.nf
\fCstatic const Rule rules[] = {
  RULE(.instance = "term", .tags = SPTAG(Sp1))
  ...
};
static const char *scratchpads[][32] = {
[Sp1] = { "st", "-n", "term", NULL }, /* terminal */
...
};
static const Key keys[] = {
  SPKEYS(MOD,    XK_s,    Sp1)
  ...
};
\fP
.fi
.RE
.SS "A script that handles clicking"
.PP
\fBNOTE\fP: Before calling \fCexit\fP it does \fCecho ''\fP; it is important to \fCecho\fP something
(even \fC''\fP) to ’\fInotify’\fP demwm that the block has changed.


.RS
.nf
\fC#!/bin/sh

# handle demwm blocks
case $BLOCK_BUTTON in
  1) notify-send "You've clicked mouse button $BLOCK_BUTTON" ;;
  2) notify-send "Right click" ;;
  3) notify-send "Middle click" ;;
  4) pamixer --allow-boost -i 1 ;; # volume up
  5) pamixer --allow-boost -d 1 ;; # volume down
  6) "$TERMINAL" -e "$EDITOR" "$0" ;; # edit the block
  7) "$TERMINAL" -e "$EDITOR" "$0" & ;; # edit the block without locking it
esac

# If nothing is playing, don't output anything
[ "$(mpc status '%state%')" = 'paused' ] && echo '' && exit

# dislpay text
echo "Playing: $(mpc current --format '[[%artist% - ]%title%]|[%file%]')"
\fP
.fi
.RE
.SS "IPC examples"
.RS
.nf
\fC$ demwm incrgaps +10
$ demwm incrgaps -10
$ demwm restart
\fP
.fi
.RE
.SS "Signaling blocks"
.RS
.nf
\fC$ demwm updateblock 8
\fP
.fi
.RE
.SS "Creating a custom scheme for a block"
.RS
.nf
\fCstatic const char *colors[][2] = {
    ...
    /* custom block schemes */
    [SchemeLast+0] = { color7,   "#222222" }, /* sb-clock */
    [SchemeLast+1] = { "ffffff", "#525252" }, /* sb-disk  */
    [SchemeLast+2] = { fg_wal,   bg_wal, }, /* sb-volume */
};

static const unsigned int alphas[][2] = {
    ...
    /* custom blocks schemes */
    [SchemeLast+0] = { Solid,  baralpha }, /* sb-clock */
    [SchemeLast+1] = { Solid,  baralpha }, /* sb-disk */
    [SchemeLast+1] = { Solid,  baralpha }, /* sb-volume */
};

static const Block blocks[] = {
    ...
    { SchemeLast+0, "sb-clock",  20,   1},
    { SchemeLast+1, "sb-disk",   9000, 2},
    { SchemeStatus, "sb-volume", 0,    8},
};
\fP
.fi
.RE
.SH "ISSUES"
.PP
Java applications which use the XToolkit/XAWT backend may draw grey windows
only. The XToolkit/XAWT backend breaks ICCCM-compliance in recent JDK 1.5 and
early JDK 1.6 versions, because it assumes a reparenting window manager.
Possible workarounds are using JDK 1.4 (which doesn’t contain the XToolkit/XAWT
backend) or setting the environment variable \fCAWT_TOOLKIT=MToolkit\fP (to use the
older Motif backend instead) or running \fCxprop \-root \-f _NET_WM_NAME 32a \-set
_NET_WM_NAME LG3D\fP or \fCwmname LG3D\fP (to pretend that a non-reparenting window
manager is running that the XToolkit/XAWT backend can recognize) or when using
OpenJDK setting the environment variable \fC_JAVA_AWT_WM_NONREPARENTING=1\fP
.SH "SEE ALSO"
.PP
dwm(1), poll(3), exec(3)
.SH "BUGS"
.PP
\fIhttps://github.com/explosion-mental/demwm\fP
.br
\fIhttps://codeberg.org/explosion-mental/demwm\fP
